SYSTEM:
  NUM_GPU: 4
MODEL:
  N_RESBLOCKS: 20
  N_RESGROUPS: 10
  BLOCK_TYPE: mbconv
  SE_REDUCTION: 4
  PLANES: 64
DATASET:
  DATA_SCALE: [2]
  OUT_PATCH_SIZE: 48
SOLVER:
  NAME: AdamW
  BASE_LR: 1e-3
  WEIGHT_DECAY: 5e-4
  WARMUP_ITERS: 1000
